# Using the node alpine image
image: node:10.15.2

stages:
  - install
  - test
  - publish

# JOBS

Install:
  stage: install
  script:
    - yarn
    - yarn bootstrap
  artifacts:
    paths:
      - node_modules/
      - packages/eslint/node_modules
      - packages/utils/node_modules
    expire_in: 10 minutes

Test:
  stage: test
  script:
    - yarn lint
    - yarn test

Publish:
  stage: publish
  only:
    - master
    - 140-sr-rebase
  script:
    - yarn release
