# Using the node alpine image
image: node:10.15.2

stages:
  - install
  - test
  - publish
  - changelog

# JOBS

Install:
  stage: install
  script:
    - yarn
  artifacts:
    paths:
      - node_modules/
      - packages/eslint/node_modules
      - packages/utils/node_modules
    expire_in: 10 minutes

Test:
  stage: test
  only:
    - tags
  script:
    - yarn lint
    - yarn test

Publish:
  stage: publish
  only:
    - master
    - 140-sr-rebase
  script:
    - git remote set-url origin https://${GITLAB_CI_USER}:${GITLAB_CI_TOKEN}@git.manomano.tech/core-utils/js-tools.git
    - git config user.email "$GIT_AUTHOR_EMAIL"
    - git config user.name "$GIT_AUTHOR_NAME"

    - git checkout 140-sr-rebase
    - git pull

    - npm run lerna-version
    - npm run publish

Generate Changelog:
  stage: changelog
  only:
    - master
  script:
    - yarn semantic-release
