# Using the node alpine image
image: node:10.15.2

stages:
  - install
  - test
  - changelog
  - publish

# JOBS

Install:
  stage: install
  script:
    - yarn
  artifacts:
    paths:
      - node_modules/
      - packages/eslint/node_modules
      - packages/utils/node_modules
    expire_in: 10 minutes

Test:
  stage: test
  script:
    - yarn lint
    - yarn test

Generate Changelog:
  stage: changelog
  only:
    - tags
  script:
    - yarn semantic-release

Publish-On-NPM:
  stage: publish
  script:
    - git config --global user.email "matthieu@manomano.com"
    - git config --global user.name "matthieu"
    - git checkout 140-semantic-release
    - git pull
    - git remote -v
    - npm run version
    - npm run publish
