# Using the node alpine image
image: node:10.15.2

stages:
  - install
  - test
  - changelog
  - publish

# JOBS

Install:
  stage: install
  script:
    - yarn
  artifacts:
    paths:
      - node_modules/
      - packages/eslint/node_modules
      - packages/utils/node_modules
    expire_in: 10 minutes

Test:
  stage: test
  only:
    - tags
  script:
    - yarn lint
    - yarn test

Generate Changelog:
  stage: changelog
  only:
    - tags
  script:
    - yarn semantic-release

Publish-On-NPM:
  stage: publish
  script:
    - git remote set-url origin https://${GITLAB_CI_USER}:${GITLAB_CI_TOKEN}@git.manomano.tech/core-utils/js-tools.git
    - git config user.email "$GIT_AUTHOR_EMAIL"
    - git config user.name "$GIT_AUTHOR_NAME"
    - git checkout 140-sr-rebase
    - git pull
    - git remote -v
    - npm run version
    - npm run publish --dry-run
